auto: true
server: true
paginate: 20
pigments: true
name: Ruby Lugdunum 2012
description: The French Ruby Conference June, 22nd-23rd 2012 in Lyon
url: http://rulu.eu
exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]